### PR TITLE
Resurrection Update v1.2: Visual Overhaul

### PR DESCRIPTION
**Pull request by ndo360**
This is a major updated adding a map from the abandoned 'Ricochet Source' mod. The map  (Including it's models and textures) were created by my, presumably late, friend Chris. 
As one of the staff member of (Now defunct) 'Ricochet Source' I decided to port the finished beta map for this gamemode.
I also used 'Ricochet Source's disc and powerup models.
Fixed one error (Check readme for details)
Lastly added a new screenshot showcasing the map. (In background folder)

Ptown2... If you can I need you to help with powerup and the bounce code. Hope you can help

With the help of some facepunch members I managed to get part of the bounce code working, except it does lose velocity, bounce infinitely, and ricochets off the end of the map. (For those reasons the Max.Bounces is still set to 1)

### CODE REVIEW

**Comment by ptown2** [comment]
I can't merge this due to the fact there are some conflicting files, I dunno why that happened, but can't seem to fix it without seeing the web editor being a huge mess.

Conflicting files:
- README.md
- entities/entities/powerup__base/init.lua
- entities/entities/projectile_disc/init.lua
- entities/weapons/weapon_disc.lua
- gamemode/init.lua

**Comment by ndo360** [comment]
Try removing those files and then murge.

**Comment by ndo360** [comment]
Removing them from your repository, as my files should be more up to date.

**Comment by ptown2** [comment]
I'll solve this issue command line wise since deleting made it worse, oh well. Give me a few minutes.

**Comment by ndo360** [comment]
Hopefully you get the murge working, also try testing the new beta map and see what you think! ^-^

**Comment by ndo360** [comment]
I'm going to redo the pull request as now those files are gone.

**Pull request closed without merging**
